/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#6bff8f',
        'surface-container-highest': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#930013',
        'error-container': '#ffdad6',
        'on-surface': '#191c1d',
        'on-tertiary': '#ffffff',
        'primary-container': '#4a9eed',
        'on-background': '#191c1d',
        'tertiary-container': '#ff6862',
        'surface-variant': '#e1e3e4',
        surface: '#f8f9fa',
        'on-secondary': '#ffffff',
        'on-primary-container': '#003359',
        secondary: '#006e2f',
        'on-surface-variant': '#404751',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#005321',
        'surface-container': '#edeeef',
        'on-secondary-fixed': '#002109',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#ffdad7',
        tertiary: '#b91a24',
        'secondary-container': '#6bff8f',
        'tertiary-fixed-dim': '#ffb3ad',
        'secondary-fixed-dim': '#4ae176',
        'outline-variant': '#c0c7d3',
        'on-secondary-container': '#007432',
        'inverse-primary': '#9dcaff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#410004',
        'on-primary': '#ffffff',
        primary: '#0061a2',
        'surface-tint': '#0061a2',
        'surface-bright': '#f8f9fa',
        'surface-container-low': '#f3f4f5',
        'surface-container-high': '#e7e8e9',
        background: '#f8f9fa',
        'primary-fixed-dim': '#9dcaff',
        'surface-dim': '#d9dadb',
        'inverse-surface': '#2e3132',
        'on-tertiary-container': '#6b000b',
        'on-primary-fixed': '#001d35',
        'on-primary-fixed-variant': '#00497c',
        outline: '#707882',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed': '#d1e4ff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'clinical-lift': '0px 12px 32px rgba(25,28,29,0.04)',
      },
    },
  },
  plugins: [],
};
